# Copyright 2016, Yahoo Inc.
# Licensed under the terms of the New BSD License. Please see associated LICENSE file for terms.

CREATE TABLE ANSWERS
(
QID VARCHAR(256),
PARTICIPANTNAME VARCHAR(64),
SYSTEMNAME VARCHAR(64),
SYSTEMUNIQUEID VARCHAR(128),
ANSWERCONTENT VARCHAR(2048),
RESOURCES VARCHAR(2048),
TITLESPANS VARCHAR(1024),
BODYSPANS VARCHAR(1024),
QUESTIONSUMMARY VARCHAR(512),
RESPONSEDURATION BIGINT,
REPORTEDDURATION BIGINT
);

CREATE UNIQUE INDEX ANSWERSUNIQUEINDEX ON ANSWERS
(
QID, SYSTEMUNIQUEID
);

CREATE INDEX ANSWERSQIDINDEX ON ANSWERS
(
QID
);


CREATE TABLE WHYNOTANSWERED
(
QID VARCHAR(256),
PARTICIPANTNAME VARCHAR(64),
SYSTEMNAME VARCHAR(64),
SYSTEMUNIQUEID VARCHAR(128),
DISCARDREASON VARCHAR(256)
);

CREATE UNIQUE INDEX WHYNOTANSWEREDUNIQUEINDEX ON WHYNOTANSWERED
(
QID, SYSTEMUNIQUEID
);

CREATE INDEX WHYNOTANSWEREDQIDINDEX ON WHYNOTANSWERED
(
QID
);


CREATE TABLE BADRESPONSE
(
QID VARCHAR(256),
PARTICIPANTNAME VARCHAR(64),
SYSTEMNAME VARCHAR(64),
SYSTEMUNIQUEID VARCHAR(128),
EXCEPTIONMESSAGES VARCHAR(2048)
);

CREATE UNIQUE INDEX BADRESPONSEUNIQUEINDEX ON BADRESPONSE
(
QID, SYSTEMUNIQUEID
);

CREATE TABLE QUESTIONS
(
QID VARCHAR(256),
TITLE VARCHAR(2048),
BODY VARCHAR(5120),
CATEGORY VARCHAR(512),
PUBLISHEDDATE BIGINT
);

CREATE UNIQUE INDEX QUESTIONSUNIQUEINDEX ON QUESTIONS
(
QID
);

